Iter18
KartoonYoko/go-url-shortener pull request #18
Opened 2024-03-31 04:41 UTC by KartoonYoko

2024-04-02 08:55 UTC, tmvrus requested changes

2024-04-02 08:55 UTC, tmvrus commented on internal/controller/http/controller_test.go
> +	}
а что проверяет этот бенчмарк?

2024-04-02 08:55 UTC, tmvrus commented on internal/controller/http/controller.go
> +	// server := &http.Server{Addr: c.conf.BootstrapNetAddress, Handler: c.router}
закоментированный код в рабочем проекте - дурной тон

2024-04-03 00:04 UTC, KartoonYoko commented on internal/controller/http/controller_test.go
> +	}
Добавил осмысленный бенчмарк

2024-04-04 16:43 UTC, tmvrus approved these changes

2024-04-04 21:37 UTC, merged