Iter9
KartoonYoko/go-url-shortener pull request #9
Opened 2024-01-01 07:37 UTC by KartoonYoko

2024-01-05 11:15 UTC, tmvrus requested changes
где реализация decompressRequestGZIPMiddleware /compressResponseGZIPMiddleware ?

2024-01-05 11:15 UTC, tmvrus commented on internal/controller/http/controller.go
> +	res, err := json.Marshal(&response)
в Marshal не обязательно передавать ссылку, будет работать и без &

2024-01-08 09:08 UTC, KartoonYoko commented on internal/controller/http/controller.go
> +	res, err := json.Marshal(&response)
реализации находятся в internal/controller/http/middleware_compress.go на 77 и 131

2024-01-09 19:12 UTC, tmvrus approved these changes

2024-01-13 08:36 UTC, merged